### ISSUE TITLE
raise "wrong number of arguments(given 1, expected 0)" in Rack::Builder#use

### ISSUE THREAD

**Issue by hanasuke** [rack/rack#1482]
Hi.

I'm updating gems used by Sinatra app on Ruby 2.3.5.
After updated Sinatra from '1.4.7' to '2.0.7' and rack from '1.6.8' to '2.0.8', and run `bundle exec rspec`, I got results such as:
```
     Failure/Error: subject { get(base_url, nil, header) }
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
     Shared Example Group: "XXX" called from ./spec/some/spec.rb
     # ./vendor/bundle/ruby/2.3.0/gems/rack-2.0.8/lib/rack/builder.rb:86:in `initialize'
     # ./vendor/bundle/ruby/2.3.0/gems/rack-2.0.8/lib/rack/builder.rb:86:in `new'
     # ./vendor/bundle/ruby/2.3.0/gems/rack-2.0.8/lib/rack/builder.rb:86:in `block in use'
     # ./vendor/bundle/ruby/2.3.0/gems/rack-2.0.8/lib/rack/builder.rb:147:in `block in to_app'
     # ./vendor/bundle/ruby/2.3.0/gems/rack-2.0.8/lib/rack/builder.rb:147:in `each'
     # ./vendor/bundle/ruby/2.3.0/gems/rack-2.0.8/lib/rack/builder.rb:147:in `inject'
     # ./vendor/bundle/ruby/2.3.0/gems/rack-2.0.8/lib/rack/builder.rb:147:in `to_app'
     # ./vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1488:in `new'
     # ./vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1477:in `prototype'
     # ./vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1502:in `block in call'
     # ./vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1729:in `synchronize'
     # ./vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1502:in `call'
     # ./vendor/bundle/ruby/2.3.0/gems/rack-test-1.1.0/lib/rack/mock_session.rb:29:in `request'
     # ./vendor/bundle/ruby/2.3.0/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
     # ./vendor/bundle/ruby/2.3.0/gems/rack-test-1.1.0/lib/rack/test.rb:129:in `custom_request'
     # ./vendor/bundle/ruby/2.3.0/gems/rack-test-1.1.0/lib/rack/test.rb:58:in `get'
```
I think, the error raises from this line: https://github.com/rack/rack/blob/master/lib/rack/builder.rb#L102

Before updating these gems, I've never been get such errors.
Is this error related to this gem or the other gem?
Or, is it the bug of my apps?

# system configuration
- ruby: 2.3.5p376
- rack (2.0.8)
- sinatra (2.0.7)
